### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'win32com'


### ISSUE THREAD

**Issue by baditaflorin** [Amphibitus/zoomtopaste#2]
Couldn't load plugin 'zoomtopaste' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/zoomtopaste/__init__.py", line 36, in classFactory
    from .zoomtopaste import zoomtopaste
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/zoomtopaste/zoomtopaste.py", line 31, in <module>
    from win32com.client import Dispatch
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'win32com'

```
zoomtopaste 3.0.2, QGIS 3.4.5-Madeira on Darwin 19.6.0

**Comment by Amphibitus** [comment]
Hey,

I am sorry ther is no sotution. ZoomtoPaste only run on Windows because the unit win32.com is in use.
